### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by tajmone** [phracker/f0ntbin#1]
Thanks for this project, it's really good to see this font collection preserverd.

These fonts used to be available [bmf.php5.cz](http://bmf.php5.cz/), but now it seems the site is not serving them properly. This site also mentions Daniel Guldkrans's collection, and that they are freeware. Its disclaimer goes:

> The bitmap fonts published here are of two origins:
> - First are the pictures of fonts gathered by Daniel Guldkrans (http://www.algonet.se/~guld1/) and this is moreless their backup.
> - Second part are the fonts in BMF format converted by me.
>
> I suppose all bitmap fonts exposed in here to be freeware. Nevertheless, if you (likely) are an author of any of these fonts and do not wish font to be here, just give me a sign and I'll fix it for you.

Unfortunately I never had a chance to see the original Guldkran's website, and now the link at [www.algonet.se](http://www.algonet.se/~guld1/freefont.htm) is dead, and the site is [not archived](https://web.archive.org/web/*/http://www.algonet.se/~guld1/freefont.htm) on Wayback Machine due to robots.txt settings.

Do you have an idea what the license for these fonts is? It's known that they are freeware, but how would that translate into a typical open source license? Public domain? CC?

If you could attach a permissive license to this project it would make it easier to incorporate it in other projects and duely credit their author. Obviously, the best solution would be to contact the author — but my guess is that these fonts might be from many different authors, and that Guldkran created a collection of them.

My guess is that in similar cases, with resources that have been shared openly for ages in circles to which their authors belonged, and therefore consented to the practice, these resources are to considered Public Domain — or best, use the [Unlicense template](http://unlicense.org/), which also covers those countries in which Public Domain bears no legal status. Basically, they should belong to the same category of most of the text docs and Ascii Art of the BBS era.

Since these fonts are freeware, and possibly public domain, you could freely attach a similar license to the project. Probably also adding a disclaimer like the one quoted from [bmf.php5.cz](http://bmf.php5.cz/) would be good.

I would like to create a repository gathering pixel art resouces, and attach to it a permissive license, and I'd love to include these fonts and credit you and this project, but also the original creator of the collection and the authors (wherever possible).

What's your opinion on this?

**Comment by phracker** [comment]
Hey there, glad someone else is interested in preserving this kind of thing. Forgot all about this issue, my bad. This is just a mirror, I ought to add a disclaimer to the readme. It'd be an exceptionally difficult task to issue this content under a permissive license as it originates from many creators across many jurisdictions, and I have no means of contacting them. I'd love to put it in the public domain but it's virtually impossible to do the legwork necessary to do so.

Do what you'd like, but I lack the requisite legal knowhow to make any kind of claim regarding the copyright status of this project.

**Comment by tajmone** [comment]
Thanks anyway!

**Comment by tomtebloss** [comment]
So, happen to find this thread. I am Daniel Guldkrans, the collector of the font/site that vanished. To answer the question: The fonts was ripped from intros/demos on the Atari and they where distributed as freeware, PD. However some are from games like Wings of  Death, Prehistoric Tale, Xenon 2, Magic Pockets to name a few, and is probably not freeware. Rather abandonware at this point. I had my site up for almost 20 years I think and never got any copyright claims.

**Comment by tajmone** [comment]
Thanks a lot for clarifications Daniel! Nice to hear from you.
